at layer 2 i thought of: the ability that user can save different regions of the image with different general settings and add them together pixel-wise to create the result image; all step by step as mentioned with (i wouldve used) fragments instead of multiple slides on the same screen; the focus is on developing a one-step-at-a-time mindset.
2) forward pass-> layer 8 gives:
                      android.content.ActivityNotFoundException: Unable to find explicit activity class {zar.masih.opticalcontentextractor/zar.masih.opticalcontentextractor.InpaintActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?

2) at the end of the procedure i need another activity:
remove the n biggest objects;